### PR TITLE
Run all specs filtered by tags

### PR DESCRIPTION
**Pull request by NicholasTD07**
- Add function `RunAllSpecsFilteredByTags`
- Add key mapping example
- Add a section in README.md to explain how to use it

### CODE REVIEW

**Comment by adamgeorgeson** [comment]
👍  Just been looking at how to do this in vim-rspec and came across your PR.

**Review by adamgeorgeson — APPROVED** [review]

**Comment by NicholasTD07** [comment]
@adamgeorgeson Thanks! It has been so long that I almost forgot this PR if it's not your comment. Glad it helps.

**Comment by thewatts** [comment]
@NicholasTD07 && @adamgeorgeson :) was just looking for this functionality.

Anything I can do to help this get merged in?

**Comment by NicholasTD07** [comment]
@thewatts To be honest, I have no idea since no maintainer has said anything about this PR yet. When I was using RSpec, I used [my own fork](https://github.com/NicholasTD07/vim-rspec).

**Comment by gylaz** [comment]
I'm hesitant to add support for tags to the plugin that requires this much code. The purpose of the plugin is to be simple, yet usable. Can this be achieved similar to how `--only-failures` has been customized here: https://github.com/thoughtbot/vim-rspec/pull/125#issuecomment-274349145 ?

**Comment by NicholasTD07** [comment]
Sorry guys... I haven't been using vim-rspec for years and thus just never came back to this PR. Closing this PR for now.

**Pull request closed without merging**
