### PR TITLE
Add iterm2 support

### PR DESCRIPTION
**Pull request by jasonm23**

### CODE REVIEW

**Comment by jasonm23** [comment]
Let me know if you want me to squash the two commits into one.

**Comment by gylaz** [comment]
Thanks @jasonm23, but I'm curious about your use-case. iTerm2 is already supported via `bin/os_x_iterm` script.

**Comment by jasonm23** [comment]
It's not.  ITerm suffers from a bit of naming issues.

The ITerm app is the general release and is in V.2x

ITerm2 is the bundle name on the nightlies ...

Confused?  I am.

If you grab a nightly zip the app bundle is still called ITerm.app but it will run as Iterm2 (the bundle id)

They should really sort it out!  Anyway suffice to say the two versions are NOT AppleScript compatible.  The old terminal and terminals objects are no longer there.

If you add iterm2.app (renamed nightly) to the AppleScript Editor Library, you will get the docs for the currevt API.

I'll be happy to assist while this is all fresh in my mind.

**Comment by gylaz** [comment]
Will the official name become `iTerm2` going forward? If only the nightly build is named that, and it will be renamed before they cut a stable release (maybe it's a bug), then I don't think it should be a concern of `vim-rspec` to support that nightly build situation.

**Comment by jasonm23** [comment]
It is to become Iterm2

**Comment by gylaz** [comment]
Makes sense to merge it the. Do you mind squashing into 1 commit?

**Comment by jasonm23** [comment]
Sure thing.

**Comment by jasonm23** [comment]
I'll add a note and links re:iterm2 in the commit and comments on the script itself.  To clear up any FAQ / ambiguities.

**Comment by jasonm23** [comment]
Squashed and updated, in the pipe 5 by 5

**Comment by jasonm23** [comment]
https://www.youtube.com/watch?v=8dXc2W1uWck

**Comment by gylaz** [comment]
> https://www.youtube.com/watch?v=8dXc2W1uWck

Ah, that's where Starcraft got it from!

Do you mind adding the new runner to the README (under "Custom runners")?

**Comment by jasonm23** [comment]
README update :)

**Comment by gylaz** [comment]
Excellent work, @jasonm23! Merged as f733ab32702577ad799e3cd4095aa0bd5bcaf582.

**Comment by jasonm23** [comment]
Thank you, hth

**Pull request closed without merging**
